version: '4.3.0-{build}'
image: Visual Studio 2015
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore ReasonCodeExample.XPathInformation.sln
build:
  verbosity: minimal
test:
  categories:
    except:
    - Integration
artifacts:
- path: ReasonCodeExample.XPathInformation/bin/release/*.vsix
  name: VSIX